### ISSUE TITLE
Configure version

### ISSUE THREAD

**Issue by Qbandev** [env0/checkov-plugin#1]
Is it possible to add a `version ` option for the plugin to choose the checkov version? It is already done for the other plugins like [tflint](https://github.com/env0/env0-tflint-plugin) and [tfsec](https://github.com/env0/env0-tfsec-plugin).

**Comment by burib** [comment]
would be also good to be able to cache the step downloading tfsec, checkov, etc.

**Comment by Qbandev** [comment]
I opened the following PR #2 to fix this issue
